import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { randomBytes } from "node:crypto";

export function generateDockerInfra(dir: string, coordinatorPort: number): void {
  const pgPassword = randomBytes(24).toString("hex");

  const compose = `# OpenSpawn Infrastructure
# Run: docker compose up -d

services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: openspawn
      POSTGRES_USER: openspawn
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openspawn"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
`;

  const envFile = `# OpenSpawn Environment
# Generated by openspawn init --deploy

POSTGRES_PASSWORD=${pgPassword}
DATABASE_URL=postgresql://openspawn:${pgPassword}@localhost:5432/openspawn
REDIS_URL=redis://localhost:6379
OPENSPAWN_PORT=${coordinatorPort}
`;

  writeFileSync(join(dir, "docker-compose.yml"), compose);
  writeFileSync(join(dir, ".env"), envFile);
}
