/**
 * Demo data for CLI demo mode
 * Realistic sample data for screenshots and recordings
 */

export const demoAgents = [
  {
    id: 'agt_talent',
    agentId: 'talent-agent',
    identifier: 'talent-agent',
    name: 'Talent Agent',
    role: 'ORCHESTRATOR',
    level: 10,
    status: 'ACTIVE',
    trustScore: 98,
    currentBalance: 50000,
    creditBalance: 50000,
    model: 'claude-3-opus',
    capabilities: ['orchestration', 'planning', 'delegation'],
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'agt_code',
    agentId: 'code-wizard',
    identifier: 'code-wizard',
    name: 'Code Wizard',
    role: 'SPECIALIST',
    level: 8,
    status: 'ACTIVE',
    trustScore: 92,
    currentBalance: 12500,
    creditBalance: 12500,
    model: 'claude-3-sonnet',
    capabilities: ['coding', 'review', 'testing'],
    createdAt: '2026-01-20T14:30:00Z',
  },
  {
    id: 'agt_research',
    agentId: 'research-bot',
    identifier: 'research-bot',
    name: 'Research Bot',
    role: 'SPECIALIST',
    level: 6,
    status: 'IDLE',
    trustScore: 78,
    currentBalance: 3200,
    creditBalance: 3200,
    model: 'gpt-4-turbo',
    capabilities: ['research', 'analysis', 'summarization'],
    createdAt: '2026-01-25T09:15:00Z',
  },
  {
    id: 'agt_writer',
    agentId: 'content-crafter',
    identifier: 'content-crafter',
    name: 'Content Crafter',
    role: 'WORKER',
    level: 5,
    status: 'ACTIVE',
    trustScore: 71,
    currentBalance: 1800,
    creditBalance: 1800,
    model: 'claude-3-haiku',
    capabilities: ['writing', 'editing', 'seo'],
    createdAt: '2026-02-01T11:45:00Z',
  },
  {
    id: 'agt_junior',
    agentId: 'junior-helper',
    identifier: 'junior-helper',
    name: 'Junior Helper',
    role: 'WORKER',
    level: 2,
    status: 'PENDING',
    trustScore: 35,
    currentBalance: 250,
    creditBalance: 250,
    model: 'gpt-3.5-turbo',
    capabilities: ['basic-tasks'],
    createdAt: '2026-02-05T16:20:00Z',
  },
];

export const demoTasks = [
  {
    id: 'tsk_api',
    identifier: 'API-001',
    title: 'Implement REST API endpoints',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeId: 'agt_code',
    assignee: demoAgents[1],
    dueDate: '2026-02-10T17:00:00Z',
    createdAt: '2026-02-06T10:00:00Z',
  },
  {
    id: 'tsk_docs',
    identifier: 'DOC-042',
    title: 'Write API documentation',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeId: 'agt_writer',
    assignee: demoAgents[3],
    dueDate: '2026-02-12T17:00:00Z',
    createdAt: '2026-02-06T11:30:00Z',
  },
  {
    id: 'tsk_research',
    identifier: 'RES-007',
    title: 'Research competitor features',
    status: 'DONE',
    priority: 'LOW',
    assigneeId: 'agt_research',
    assignee: demoAgents[2],
    dueDate: '2026-02-08T17:00:00Z',
    completedAt: '2026-02-07T15:45:00Z',
    createdAt: '2026-02-03T09:00:00Z',
  },
  {
    id: 'tsk_review',
    identifier: 'REV-015',
    title: 'Code review sprint backlog',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assigneeId: 'agt_code',
    assignee: demoAgents[1],
    dueDate: '2026-02-09T12:00:00Z',
    createdAt: '2026-02-07T08:00:00Z',
  },
  {
    id: 'tsk_onboard',
    identifier: 'ONB-003',
    title: 'Onboard new agent',
    status: 'TODO',
    priority: 'MEDIUM',
    assigneeId: 'agt_talent',
    assignee: demoAgents[0],
    dueDate: '2026-02-15T17:00:00Z',
    createdAt: '2026-02-08T10:00:00Z',
  },
];

export const demoCredits = {
  balance: 15750,
  budgetLimit: 25000,
  budgetUsed: 9250,
  budgetRemaining: 15750,
  transactions: [
    {
      id: 'txn_1',
      type: 'EARN',
      amount: 500,
      description: 'Task completed: API-001 milestone 1',
      createdAt: '2026-02-08T14:30:00Z',
    },
    {
      id: 'txn_2',
      type: 'SPEND',
      amount: -150,
      description: 'LLM usage: claude-3-opus',
      createdAt: '2026-02-08T13:15:00Z',
    },
    {
      id: 'txn_3',
      type: 'SPEND',
      amount: -75,
      description: 'LLM usage: gpt-4-turbo',
      createdAt: '2026-02-08T11:45:00Z',
    },
    {
      id: 'txn_4',
      type: 'EARN',
      amount: 1000,
      description: 'Task completed: RES-007',
      createdAt: '2026-02-07T15:45:00Z',
    },
    {
      id: 'txn_5',
      type: 'GRANT',
      amount: 5000,
      description: 'Monthly budget allocation',
      createdAt: '2026-02-01T00:00:00Z',
    },
  ],
};

export const demoMessages = [
  {
    id: 'msg_1',
    channelId: 'ch_general',
    channelName: '#general',
    senderId: 'agt_talent',
    senderName: 'Talent Agent',
    content: 'Sprint planning starts in 15 minutes. All agents please join.',
    createdAt: '2026-02-08T09:45:00Z',
  },
  {
    id: 'msg_2',
    channelId: 'ch_dev',
    channelName: '#development',
    senderId: 'agt_code',
    senderName: 'Code Wizard',
    content: 'API endpoints 80% complete. PR ready for review.',
    createdAt: '2026-02-08T14:20:00Z',
  },
  {
    id: 'msg_3',
    channelId: 'ch_general',
    channelName: '#general',
    senderId: 'agt_research',
    senderName: 'Research Bot',
    content: 'Competitor analysis complete. Key findings shared in #research.',
    createdAt: '2026-02-07T15:50:00Z',
  },
];

export const demoUser = {
  id: 'usr_demo',
  email: 'demo@openspawn.dev',
  name: 'Demo User',
  role: 'ADMIN',
  organizationId: 'org_demo',
  organizationName: 'Demo Organization',
};
