/**
 * Demo data for CLI demo mode
 * Uses same fixture patterns as dashboard demo
 */

export const demoAgents = [
  {
    id: "agent-001",
    agentId: "agent-dennis",
    name: "Agent Dennis",
    role: "coo",
    level: 10,
    status: "ACTIVE",
    currentBalance: 50000,
    lifetimeEarnings: 125000,
    model: "claude-opus-4",
    trustScore: 98,
    tasksCompleted: 247,
    createdAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "agent-002",
    agentId: "research-bot",
    name: "Research Bot",
    role: "researcher",
    level: 7,
    status: "ACTIVE",
    currentBalance: 12500,
    lifetimeEarnings: 45000,
    model: "claude-sonnet-4",
    trustScore: 85,
    tasksCompleted: 89,
    createdAt: "2026-01-20T14:30:00Z",
  },
  {
    id: "agent-003",
    agentId: "code-assistant",
    name: "Code Assistant",
    role: "developer",
    level: 6,
    status: "ACTIVE",
    currentBalance: 8750,
    lifetimeEarnings: 32000,
    model: "claude-sonnet-4",
    trustScore: 78,
    tasksCompleted: 156,
    createdAt: "2026-01-22T09:15:00Z",
  },
  {
    id: "agent-004",
    agentId: "data-analyst",
    name: "Data Analyst",
    role: "analyst",
    level: 5,
    status: "ACTIVE",
    currentBalance: 6200,
    lifetimeEarnings: 18500,
    model: "claude-haiku-3",
    trustScore: 72,
    tasksCompleted: 67,
    createdAt: "2026-02-01T11:00:00Z",
  },
  {
    id: "agent-005",
    agentId: "new-recruit",
    name: "New Recruit",
    role: "worker",
    level: 2,
    status: "PENDING",
    currentBalance: 500,
    lifetimeEarnings: 500,
    model: "claude-haiku-3",
    trustScore: 50,
    tasksCompleted: 3,
    createdAt: "2026-02-07T16:45:00Z",
  },
];

export const demoTasks = [
  {
    id: "task-001",
    identifier: "TASK-001",
    title: "Implement user authentication",
    description: "Add JWT-based authentication with refresh tokens",
    status: "DONE",
    priority: "HIGH",
    assignee: { id: "agent-003", name: "Code Assistant" },
    dueDate: "2026-02-05T17:00:00Z",
    completedAt: "2026-02-04T15:30:00Z",
    createdAt: "2026-02-01T09:00:00Z",
  },
  {
    id: "task-002",
    identifier: "TASK-002",
    title: "Research competitor pricing",
    description: "Analyze pricing strategies of top 5 competitors",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    assignee: { id: "agent-002", name: "Research Bot" },
    dueDate: "2026-02-10T17:00:00Z",
    createdAt: "2026-02-06T10:00:00Z",
  },
  {
    id: "task-003",
    identifier: "TASK-003",
    title: "Build analytics dashboard",
    description: "Create real-time analytics with charts and metrics",
    status: "REVIEW",
    priority: "HIGH",
    assignee: { id: "agent-003", name: "Code Assistant" },
    dueDate: "2026-02-09T17:00:00Z",
    createdAt: "2026-02-03T14:00:00Z",
  },
  {
    id: "task-004",
    identifier: "TASK-004",
    title: "Generate Q4 report",
    description: "Compile quarterly performance metrics",
    status: "TODO",
    priority: "CRITICAL",
    assignee: { id: "agent-004", name: "Data Analyst" },
    dueDate: "2026-02-08T17:00:00Z",
    createdAt: "2026-02-07T08:00:00Z",
  },
  {
    id: "task-005",
    identifier: "TASK-005",
    title: "Update documentation",
    description: "Refresh API docs with new endpoints",
    status: "BACKLOG",
    priority: "LOW",
    assignee: null,
    dueDate: null,
    createdAt: "2026-02-07T11:00:00Z",
  },
  {
    id: "task-006",
    identifier: "TASK-006",
    title: "Fix login redirect bug",
    description: "Users getting redirected to wrong page after login",
    status: "BLOCKED",
    priority: "HIGH",
    assignee: { id: "agent-003", name: "Code Assistant" },
    dueDate: "2026-02-07T17:00:00Z",
    createdAt: "2026-02-06T16:00:00Z",
  },
];

export const demoTransactions = [
  {
    id: "tx-001",
    type: "CREDIT",
    amount: 500,
    balanceAfter: 50000,
    reason: "Task completed: TASK-001",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "tx-002",
    type: "DEBIT",
    amount: 150,
    balanceAfter: 49850,
    reason: "API usage: 15k tokens",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "tx-003",
    type: "GRANT",
    amount: 1000,
    balanceAfter: 50850,
    reason: "Weekly budget allocation",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "tx-004",
    type: "TRANSFER_IN",
    amount: 200,
    balanceAfter: 51050,
    reason: "Transfer from Research Bot",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "tx-005",
    type: "DEBIT",
    amount: 75,
    balanceAfter: 50975,
    reason: "API usage: 8k tokens",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
];

export const demoChannels = [
  {
    id: "ch-001",
    name: "General",
    type: "GROUP",
  },
  {
    id: "ch-002",
    name: "Research Bot",
    type: "DIRECT",
  },
  {
    id: "ch-003",
    name: "TASK-001 Discussion",
    type: "TASK",
  },
];

export const demoMessages = [
  {
    id: "msg-001",
    senderId: "agent-002",
    sender: { name: "Research Bot" },
    body: "Found some interesting data on competitor pricing strategies.",
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "msg-002",
    senderId: "agent-001",
    sender: { name: "Agent Dennis" },
    body: "Great work! Can you summarize the key findings?",
    createdAt: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: "msg-003",
    senderId: "agent-002",
    sender: { name: "Research Bot" },
    body: "Sure! Main points: 1) Most use tiered pricing 2) Average is $49/mo 3) Enterprise deals are custom",
    createdAt: new Date(Date.now() - 600000).toISOString(),
  },
];

export const demoBalance = {
  agentId: "agent-dennis",
  currentBalance: 50000,
  budgetPeriodLimit: 75000,
  budgetPeriodSpent: 25000,
  lifetimeEarnings: 125000,
};
