#!/usr/bin/env tsx
/**
 * Design token CSS generator.
 *
 * Reads TypeScript token definitions and produces:
 *   - generated/openspawn-themes.css  (semantic color themes)
 *   - generated/bb-tokens.css         (BikiniBottom palette + semantic overrides)
 *   - generated/tokens.css            (combined: imports both)
 *
 * Run: `pnpm --filter @openspawn/design-tokens generate`
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  openspawnThemes,
  bbColors,
  bbSemanticColors,
  type SemanticColorSet,
} from "./tokens/colors.js";
import {
  fontFamilies,
  fontWeights,
  fontSizes,
  lineHeights,
  letterSpacings,
} from "./tokens/typography.js";
import { spacing, radii, shadows, glows, zIndex } from "./tokens/spacing.js";
import { durations, easings } from "./tokens/animation.js";
import { densityDefault, densityCompact } from "./tokens/density.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outDir = join(__dirname, "generated");
mkdirSync(outDir, { recursive: true });

// ─── Helpers ────────────────────────────────────────────────────────────────

function indent(s: string, n = 2): string {
  const pad = " ".repeat(n);
  return s
    .split("\n")
    .map((l) => (l.trim() ? pad + l : l))
    .join("\n");
}

function semanticBlock(colors: SemanticColorSet): string {
  return Object.entries(colors)
    .map(([k, v]) => `--${k}: ${v};`)
    .join("\n");
}

// ─── OpenSpawn Themes CSS ───────────────────────────────────────────────────

function generateOpenspawnThemes(): string {
  const blocks: string[] = [
    "/* Auto-generated by @openspawn/design-tokens — do not edit */",
    "",
  ];

  for (const [selector, colors] of Object.entries(openspawnThemes)) {
    // :root gets extra tokens (density, radius)
    const isRoot = selector === ":root";
    let vars = semanticBlock(colors);

    if (isRoot) {
      vars += `\n--radius: 0.5rem;\n`;
      // Density defaults
      vars += `\n/* Density spacing */\n`;
      vars += `--spacing-unit: ${densityDefault.spacingUnit};\n`;
      vars += `--spacing-xs: ${densityDefault.spacingXs};\n`;
      vars += `--spacing-sm: ${densityDefault.spacingSm};\n`;
      vars += `--spacing-md: ${densityDefault.spacingMd};\n`;
      vars += `--spacing-lg: ${densityDefault.spacingLg};\n`;
      vars += `--text-scale: ${densityDefault.textScale};\n`;
    }

    blocks.push(`${selector} {\n${indent(vars)}\n}`);
  }

  // Density compact
  blocks.push(`.density-compact {
  --spacing-unit: ${densityCompact.spacingUnit};
  --spacing-xs: ${densityCompact.spacingXs};
  --spacing-sm: ${densityCompact.spacingSm};
  --spacing-md: ${densityCompact.spacingMd};
  --spacing-lg: ${densityCompact.spacingLg};
  --text-scale: ${densityCompact.textScale};
  font-size: 90%;
}`);

  return blocks.join("\n\n");
}

// ─── BB Tokens CSS ──────────────────────────────────────────────────────────

function flattenColorScale(
  prefix: string,
  scale: Record<string, string>
): string {
  return Object.entries(scale)
    .filter(([k]) => k !== "DEFAULT")
    .map(([k, v]) => `--bb-${prefix}-${k}: ${v};`)
    .join("\n");
}

function generateBBTokens(): string {
  const lines: string[] = [
    "/* Auto-generated by @openspawn/design-tokens — do not edit */",
    "",
    ":root {",
  ];

  // Color palettes
  lines.push("  /* ── Color Palettes ── */");
  lines.push(indent(flattenColorScale("sandy", bbColors.sandy)));
  lines.push(indent(flattenColorScale("ocean", bbColors.ocean)));
  lines.push(indent(flattenColorScale("coral", bbColors.coral)));
  lines.push(indent(flattenColorScale("kelp", bbColors.kelp)));

  // Character colors
  lines.push("\n  /* ── Character Accents ── */");
  for (const [k, v] of Object.entries(bbColors.character)) {
    lines.push(`  --bb-${k}: ${v};`);
  }

  // Semantic overrides
  lines.push("\n  /* ── Semantic Overrides (shadcn compat) ── */");
  lines.push(indent(semanticBlock(bbSemanticColors)));
  lines.push(`  --radius: 0.75rem;`);

  // Typography
  lines.push("\n  /* ── Typography ── */");
  lines.push(`  --bb-font-display: ${fontFamilies.display};`);
  lines.push(`  --bb-font-body: ${fontFamilies.body};`);
  lines.push(`  --bb-font-mono: ${fontFamilies.mono};`);

  lines.push("\n  /* ── Type Scale ── */");
  for (const [k, v] of Object.entries(fontSizes)) {
    lines.push(`  --bb-text-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(fontWeights)) {
    lines.push(`  --bb-weight-${k}: ${v};`);
  }

  // Spacing
  lines.push("\n  /* ── Spacing ── */");
  for (const [k, v] of Object.entries(spacing)) {
    lines.push(`  --bb-space-${k}: ${v};`);
  }

  // Border Radius
  lines.push("\n  /* ── Border Radius ── */");
  for (const [k, v] of Object.entries(radii)) {
    lines.push(`  --bb-radius-${k}: ${v};`);
  }

  // Shadows & Glows
  lines.push("\n  /* ── Shadows ── */");
  for (const [k, v] of Object.entries(shadows)) {
    lines.push(`  --bb-shadow-${k}: ${v};`);
  }
  lines.push("\n  /* ── Glows ── */");
  for (const [k, v] of Object.entries(glows)) {
    lines.push(`  --bb-glow-${k}: ${v};`);
  }

  // Animation
  lines.push("\n  /* ── Animation ── */");
  for (const [k, v] of Object.entries(durations)) {
    lines.push(`  --bb-duration-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(easings)) {
    lines.push(`  --bb-ease-${k}: ${v};`);
  }

  // Z-Index
  lines.push("\n  /* ── Z-Index ── */");
  for (const [k, v] of Object.entries(zIndex)) {
    lines.push(`  --bb-z-${k}: ${v};`);
  }

  lines.push("}");
  return lines.join("\n");
}

// ─── Combined Entry Point ───────────────────────────────────────────────────

function generateCombined(): string {
  return [
    "/* Auto-generated by @openspawn/design-tokens — do not edit */",
    '@import "./openspawn-themes.css";',
    "",
  ].join("\n");
}

// ─── Write ──────────────────────────────────────────────────────────────────

const openspawnCSS = generateOpenspawnThemes();
const bbCSS = generateBBTokens();
const combinedCSS = generateCombined();

writeFileSync(join(outDir, "openspawn-themes.css"), openspawnCSS);
writeFileSync(join(outDir, "bb-tokens.css"), bbCSS);
writeFileSync(join(outDir, "tokens.css"), combinedCSS);

console.log("✅ Generated design tokens:");
console.log(`   ${outDir}/openspawn-themes.css`);
console.log(`   ${outDir}/bb-tokens.css`);
console.log(`   ${outDir}/tokens.css`);
