export enum SandboxEscalationReason {
  BLOCKED = "BLOCKED",
  OUT_OF_DOMAIN = "OUT_OF_DOMAIN",
  OVER_BUDGET = "OVER_BUDGET",
  LOW_CONFIDENCE = "LOW_CONFIDENCE",
  TIMEOUT = "TIMEOUT",
  DEPENDENCY = "DEPENDENCY",
}
