export enum SimulationEventType {
  AGENT_CREATED = "agent_created",
  AGENT_ACTIVATED = "agent_activated",
  AGENT_PROMOTED = "agent_promoted",
  AGENT_TERMINATED = "agent_terminated",
  AGENT_STATUS_CHANGED = "agent_status_changed",
  AGENT_DESPAWNED = "agent_despawned",
  AGENT_IDLE = "agent_idle",
  TASK_CREATED = "task_created",
  TASK_ASSIGNED = "task_assigned",
  TASK_COMPLETED = "task_completed",
  TASK_COMPLETION_REJECTED = "task_completion_rejected",
  CREDIT_EARNED = "credit_earned",
  CREDIT_SPENT = "credit_spent",
  PREHOOK_BLOCKED = "prehook_blocked",
  PREHOOK_ALLOWED = "prehook_allowed",
  SYSTEM_EVENT = "system_event",
}
