import { Command } from "commander";
import pc from "picocolors";
import { writeFileSync } from "fs";
import { join } from "path";
import { createInterface } from "readline";
import { icons } from "../lib/output.js";

interface DesignBrief {
  title: string;
  pain: string;
  statusQuo: string;
  targetUser: string;
  narrowestWedge: string;
  observation: string;
  futureFit: string;
}

const QUESTIONS = [
  {
    key: "pain" as const,
    label: "Pain",
    prompt: `What is the ${pc.bold("actual pain")}? Not the feature request — the underlying problem that makes someone's life worse today.`,
    followUp: `That sounds like a solution, not a pain. What's the ${pc.bold("problem")} that makes someone reach for that solution?`,
  },
  {
    key: "statusQuo" as const,
    label: "Status Quo",
    prompt: `What are people doing ${pc.bold("today")} to deal with this pain? If nothing — why not?`,
    followUp: `If nobody is working around it, is it actually painful enough to solve?`,
  },
  {
    key: "targetUser" as const,
    label: "Target User",
    prompt: `Who is the most ${pc.bold("specific, desperate")} user? Describe one person, one scenario.`,
    followUp: `Can you be more specific? "Developers" is too broad — describe ONE person hitting ONE wall.`,
  },
  {
    key: "narrowestWedge" as const,
    label: "Narrowest Wedge",
    prompt: `What is the ${pc.bold("smallest possible thing")} you could build that proves this is worth doing? Not an MVP — the thinnest wedge.`,
    followUp: `That still sounds like a full product. What's the ONE thing that, if it worked, proves the whole thesis?`,
  },
  {
    key: "observation" as const,
    label: "Observation",
    prompt: `What have you ${pc.bold("observed")} — in data, behavior, or the market — that others haven't?`,
    followUp: `What's the insight that makes YOUR solution different from what already exists?`,
  },
  {
    key: "futureFit" as const,
    label: "Future-Fit",
    prompt: `If this succeeds wildly and grows 100x, does it still make sense? Or are you building for ${pc.bold("today's constraints")} that won't exist in 2 years?`,
    followUp: `Think about it differently: what changes in the next 2 years that might make this approach obsolete?`,
  },
];

function askQuestion(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(`${question}\n${pc.dim(">")} `, (answer) => {
      resolve(answer.trim());
    });
  });
}

function generateBriefMarkdown(brief: DesignBrief): string {
  const date = new Date().toISOString().split("T")[0];
  return `# Design Brief: ${brief.title}

**Date:** ${date}
**Generated by:** openspawn office-hours

---

## 1. Pain
${brief.pain}

## 2. Status Quo
${brief.statusQuo}

## 3. Target User
${brief.targetUser}

## 4. Narrowest Wedge
${brief.narrowestWedge}

## 5. Unique Observation
${brief.observation}

## 6. Future-Fit
${brief.futureFit}

---

## Recommendation
<!-- Fill in after review: BUILD / RETHINK / KILL — with reasoning -->

`;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+$/g, "")
    .replace(/^-+/g, "")
    .slice(0, 60);
}

export function createOfficeHoursCommand(): Command {
  const cmd = new Command("office-hours");

  cmd
    .description("Run a scope challenge interview before building (6 forcing questions)")
    .option("-o, --output <path>", "Output file path for the design brief")
    .option("--non-interactive", "Read answers from stdin (one per line, for testing)")
    .action(async (opts: { output?: string; nonInteractive?: boolean }) => {
      const banner = `
${pc.cyan("┌──────────────────────────────────────────┐")}
${pc.cyan("│")}  ${icons.rocket} ${pc.bold(pc.white("OpenSpawn Office Hours"))}               ${pc.cyan("│")}
${pc.cyan("│")}  ${pc.dim("Scope challenge before building")}          ${pc.cyan("│")}
${pc.cyan("└──────────────────────────────────────────┘")}
`;
      console.log(banner);
      console.log(
        pc.dim(
          "Answer six forcing questions to produce a design brief.\nThe goal: make sure you're building the right thing.\n",
        ),
      );

      const rl = createInterface({
        input: process.stdin,
        output: process.stdout,
      });

      try {
        // Get the project title
        const title = await askQuestion(
          rl,
          `${pc.bold("What are you thinking about building?")} Give it a short title.`,
        );

        if (!title) {
          console.log(`\n${icons.error} No title provided. Exiting.`);
          rl.close();
          return;
        }

        console.log(`\n${pc.dim("Great. Let's challenge that idea with 6 questions.\n")}`);

        const brief: DesignBrief = {
          title,
          pain: "",
          statusQuo: "",
          targetUser: "",
          narrowestWedge: "",
          observation: "",
          futureFit: "",
        };

        for (let i = 0; i < QUESTIONS.length; i++) {
          const q = QUESTIONS[i];
          console.log(
            `\n${pc.cyan(`Question ${i + 1}/6:`)} ${pc.bold(q.label)}`,
          );
          const answer = await askQuestion(rl, q.prompt);

          if (!answer || answer.length < 10) {
            console.log(pc.yellow(`\n  ${q.followUp}`));
            const retry = await askQuestion(rl, pc.dim("Try again:"));
            brief[q.key] = retry || answer || "(no answer)";
          } else {
            brief[q.key] = answer;
          }
        }

        rl.close();

        // Generate and save the brief
        const markdown = generateBriefMarkdown(brief);
        const slug = slugify(title);
        const filename = opts.output || `design-brief-${slug}.md`;
        const filepath = join(process.cwd(), filename);

        writeFileSync(filepath, markdown);

        console.log(`\n${pc.green("━".repeat(50))}`);
        console.log(`${icons.check} ${pc.bold("Design brief saved:")} ${pc.cyan(filepath)}`);
        console.log(pc.dim("\nNext steps:"));
        console.log(pc.dim("  1. Review the brief and add your recommendation"));
        console.log(pc.dim("  2. Share with your team or reviewer agent"));
        console.log(
          pc.dim("  3. Run: openspawn preview  — to test with your agent org"),
        );
        console.log(`${pc.green("━".repeat(50))}\n`);
      } catch {
        rl.close();
        console.log(`\n${icons.error} Interview interrupted.`);
      }
    });

  return cmd;
}
