// ── Operation: 10,000 Krabby Patties ────────────────────────────────────────
// Plankton orders 10,000 Krabby Patties. The kitchen produces faster than
// Squidward can deliver, creating a classic producer-consumer bottleneck.
// ~2000 decisions over 300 ticks across 5 acts.

import type { ScenarioDefinition } from '../scenario-types.js';

export const krabbyPattiesScenario: ScenarioDefinition = {
  meta: {
    id: 'krabby-patties',
    name: 'Operation: 10,000 Krabby Patties',
    industry: 'Fast Food Empire',
    description: 'Plankton submits a massive order for 10,000 Krabby Patties. The entire Krusty Krab mobilizes. SpongeBob\'s kitchen produces faster than Squidward can deliver — a classic producer-consumer bottleneck threatens to sink the operation.',
    duration: '3 minutes',
    targetDecisions: 2000,
    tickIntervalMs: 600,
    seed: 'random',
    difficulty: 'normal',
    totalTicks: 300,
  },

  // ── Phases (5 Acts) ──────────────────────────────────────────────────────

  phases: [
    {
      id: 'the-order',
      name: 'Act 1: The Order',
      tickRange: [1, 20],
      tickIntervalMs: 500,
      unlocksEpics: ['order-intake', 'cost-tracking-setup', 'security-threat-assessment'],
      enabledEvents: ['plankton-suspicious-activity'],
      difficultyMod: 0.8,
      transition: { type: 'hybrid', tick: 20, condition: { epicCompletionPct: 50 } },
      narrative: '🦠 Plankton walks in and orders 10,000 Krabby Patties. Mr. Krabs sees dollar signs. The entire org mobilizes.',
    },
    {
      id: 'kitchen-heats-up',
      name: 'Act 2: The Kitchen Heats Up',
      tickRange: [21, 80],
      unlocksEpics: ['batch-production-pipeline', 'quality-assurance-system', 'marketing-coverage', 'parallel-security-investigation'],
      enabledEvents: ['grill-malfunction', 'ingredient-shortage', 'intern-disaster', 'plankton-suspicious-activity'],
      difficultyMod: 1.0,
      transition: { type: 'hybrid', tick: 80, condition: { epicsDone: 3 } },
      narrative: '🧽 SpongeBob decomposes the order into batches. Sandy architects the parallel pipeline. The kitchen is ON FIRE (metaphorically).',
    },
    {
      id: 'delivery-crisis',
      name: 'Act 3: Order Up! — The Delivery Crisis',
      tickRange: [60, 150],
      unlocksEpics: ['delivery-operations', 'order-tracking-ui', 'support-ticket-surge'],
      enabledEvents: ['squidward-drops-order', 'wrong-table-delivery', 'customer-complaint-wave', 'grill-malfunction', 'plankton-suspicious-activity'],
      difficultyMod: 1.5,
      transition: { type: 'hybrid', tick: 150, condition: { epicCompletionPct: 40 } },
      narrative: '🐙 Squidward is the ONLY delivery agent. 8 batches/tick vs 50 produced. The window queue grows. Chaos ensues.',
    },
    {
      id: 'the-bottleneck',
      name: 'Act 4: The Bottleneck',
      tickRange: [120, 200],
      unlocksEpics: ['resource-reallocation', 'overtime-cost-analysis', 'kitchen-idle-management'],
      enabledEvents: ['squidward-meltdown', 'customer-complaint-wave', 'overtime-budget-alert', 'wrong-table-delivery'],
      difficultyMod: 2.0,
      transition: { type: 'hybrid', tick: 200, condition: { specificEpics: ['resource-reallocation'] } },
      narrative: '🐙 "I CAN\'T DELIVER 10,000 BY MYSELF!" — 200+ batches backed up. SpongeBob\'s team idles. Mr. Krabs faces THE DECISION.',
    },
    {
      id: 'pipeline-balances',
      name: 'Act 5: The Pipeline Balances',
      tickRange: [180, 300],
      unlocksEpics: ['scaled-delivery', 'final-push', 'financial-reconciliation', 'security-final-report'],
      enabledEvents: ['customer-complaint-wave', 'plankton-suspicious-activity'],
      difficultyMod: 1.0,
      transition: { type: 'tick', tick: 300 },
      narrative: '📦 Pearl + Fred join delivery. Rate triples. Queue drains. Quality recovers. 10,000 Krabby Patties — DELIVERED.',
    },
  ],

  // ── Epics ────────────────────────────────────────────────────────────────

  epics: [
    // ── ACT 1: The Order ──────────────────────────────────────────────────

    {
      id: 'order-intake',
      title: 'Order Intake & Delegation',
      phase: 'the-order',
      domains: ['operations', 'engineering'],
      priority: 'critical',
      description: 'Plankton\'s 10,000 patty order arrives. Mr. Krabs accepts and delegates to SpongeBob (production) and Squidward (delivery).',
      taskTemplates: [
        {
          id: 'validate-order',
          title: 'Validate Order — 10,000 Krabby Patties',
          domain: 'operations',
          subtasks: [
            { title: 'Receive order from Plankton', durationRange: [1, 2] },
            { title: 'Verify payment ($$$)', durationRange: [1, 2] },
            { title: 'Mr. Krabs approval (dollar signs in eyes)', durationRange: [1, 1] },
          ],
          durationRange: [1, 2],
          reviewRequired: true,
          reviewLoop: { maxIterations: 1, weights: [90, 10, 0, 0] },
        },
        {
          id: 'delegate-production',
          title: 'Delegate to SpongeBob — Production Plan',
          domain: 'engineering',
          subtasks: [
            { title: 'Brief SpongeBob on order magnitude', durationRange: [1, 2] },
            { title: 'SpongeBob creates batch decomposition', durationRange: [2, 3] },
            { title: 'Sandy reviews pipeline architecture', durationRange: [2, 3] },
          ],
          durationRange: [1, 3],
          reviewRequired: true,
          dependsOnTasks: ['validate-order'],
          crossDeptTriggers: [
            { action: 'unlock_epic', target: 'batch-production-pipeline' },
          ],
        },
        {
          id: 'delegate-delivery',
          title: 'Delegate to Squidward — Delivery Plan',
          domain: 'operations',
          subtasks: [
            { title: 'Brief Squidward on delivery requirements', durationRange: [1, 2] },
            { title: 'Squidward reluctantly accepts', durationRange: [1, 2] },
            { title: 'Estimate delivery capacity (8/tick)', durationRange: [1, 2] },
          ],
          durationRange: [1, 2],
          reviewRequired: false,
          dependsOnTasks: ['validate-order'],
          crossDeptTriggers: [
            { action: 'unlock_epic', target: 'delivery-operations' },
          ],
        },
      ],
    },
    {
      id: 'cost-tracking-setup',
      title: 'Financial Tracking Setup',
      phase: 'the-order',
      domains: ['finance'],
      priority: 'high',
      description: 'Squilliam sets up cost tracking for the massive order.',
      taskTemplates: [
        {
          id: 'setup-cost-tracker',
          title: 'Initialize P&L Tracking',
          domain: 'finance',
          subtasks: [
            { title: 'Calculate ingredient costs per batch', durationRange: [2, 3] },
            { title: 'Set up labor cost tracking', durationRange: [2, 3] },
            { title: 'Establish margin targets', durationRange: [1, 2] },
            { title: 'Mrs. Puff opens cost ledger', durationRange: [1, 2] },
          ],
          durationRange: [1, 3],
          reviewRequired: true,
        },
        {
          id: 'revenue-projection',
          title: 'Revenue Projection',
          domain: 'finance',
          subtasks: [
            { title: 'Price × 10,000 calculation', durationRange: [1, 2] },
            { title: 'Plankton analytics on order patterns', durationRange: [2, 3] },
            { title: 'Squilliam presents projection to Krabs', durationRange: [1, 2] },
          ],
          durationRange: [1, 3],
          reviewRequired: false,
          dependsOnTasks: ['setup-cost-tracker'],
        },
      ],
    },
    {
      id: 'security-threat-assessment',
      title: 'Security: Why Does Plankton Want 10,000?',
      phase: 'the-order',
      domains: ['security'],
      priority: 'high',
      description: 'Karen flags Plankton\'s order as suspicious. Initial threat assessment.',
      taskTemplates: [
        {
          id: 'threat-assessment',
          title: 'Initial Threat Assessment',
          domain: 'security',
          subtasks: [
            { title: 'Flag order as suspicious — Plankton history', durationRange: [1, 2] },
            { title: 'Karen runs background check', durationRange: [2, 3] },
            { title: 'Mermaid Man monitors API access logs', durationRange: [2, 3] },
          ],
          durationRange: [1, 3],
          reviewRequired: true,
          crossDeptTriggers: [
            { action: 'unlock_epic', target: 'parallel-security-investigation' },
          ],
        },
      ],
    },

    // ── ACT 2: The Kitchen Heats Up ───────────────────────────────────────

    {
      id: 'batch-production-pipeline',
      title: 'Batch Production Pipeline',
      phase: 'kitchen-heats-up',
      domains: ['engineering'],
      priority: 'critical',
      description: 'SpongeBob\'s team builds and runs the parallel patty production pipeline. Target: 50 batches/tick.',
      dependsOnEpics: ['order-intake'],
      taskTemplates: [
        {
          id: 'pipeline-architecture',
          title: 'Pipeline Architecture — Sandy\'s Design',
          domain: 'engineering',
          subtasks: [
            { title: 'Design parallel grill stations', durationRange: [2, 4] },
            { title: 'Ingredient pre-staging system', durationRange: [2, 3] },
            { title: 'Batch sizing optimization (50/tick target)', durationRange: [2, 4] },
            { title: 'Assembly line choreography', durationRange: [2, 3] },
          ],
          durationRange: [2, 4],
          reviewRequired: true,
          reviewLoop: { maxIterations: 2, weights: [60, 30, 10, 0] },
        },
        {
          id: 'batch-execution-alpha',
          title: 'Batch Execution — Batches 1-2500',
          domain: 'backend',
          subtasks: [
            { title: 'Patrick fires up grills', durationRange: [2, 3] },
            { title: 'Execute batches 1-500', durationRange: [3, 5] },
            { title: 'Execute batches 501-1500', durationRange: [4, 6] },
            { title: 'Execute batches 1501-2500', durationRange: [4, 6] },
          ],
          durationRange: [2, 6],
          reviewRequired: false,
          dependsOnTasks: ['pipeline-architecture'],
          resourceCost: { 'ingredients': 25 },
        },
        {
          id: 'batch-execution-beta',
          title: 'Batch Execution — Batches 2501-5000',
          domain: 'backend',
          subtasks: [
            { title: 'Execute batches 2501-3500', durationRange: [4, 6] },
            { title: 'Execute batches 3501-4500', durationRange: [4, 6] },
            { title: 'Execute batches 4501-5000', durationRange: [3, 5] },
          ],
          durationRange: [3, 6],
          reviewRequired: false,
          dependsOnTasks: ['batch-execution-alpha'],
          resourceCost: { 'ingredients': 25 },
        },
        {
          id: 'batch-execution-gamma',
          title: 'Batch Execution — Batches 5001-7500',
          domain: 'backend',
          subtasks: [
            { title: 'Execute batches 5001-6000', durationRange: [4, 6] },
            { title: 'Execute batches 6001-7000', durationRange: [4, 6] },
            { title: 'Execute batches 7001-7500', durationRange: [3, 5] },
          ],
          durationRange: [3, 6],
          reviewRequired: false,
          dependsOnTasks: ['batch-execution-beta'],
          resourceCost: { 'ingredients': 25 },
        },
        {
          id: 'batch-execution-delta',
          title: 'Batch Execution — Batches 7501-10000',
          domain: 'backend',
          subtasks: [
            { title: 'Execute batches 7501-8500', durationRange: [4, 6] },
            { title: 'Execute batches 8501-9500', durationRange: [4, 6] },
            { title: 'Execute batches 9501-10000', durationRange: [3, 5] },
          ],
          durationRange: [3, 6],
          reviewRequired: false,
          dependsOnTasks: ['batch-execution-gamma'],
          resourceCost: { 'ingredients': 25 },
        },
      ],
    },
    {
      id: 'quality-assurance-system',
      title: 'Quality Assurance — Gary\'s QA Pipeline',
      phase: 'kitchen-heats-up',
      domains: ['engineering'],
      priority: 'high',
      description: 'Gary QAs every batch. Plankton Jr. assists (poorly).',
      taskTemplates: [
        {
          id: 'qa-framework',
          title: 'QA Framework Setup',
          domain: 'engineering',
          subtasks: [
            { title: 'Gary defines quality criteria', durationRange: [2, 3] },
            { title: 'Build batch inspection pipeline', durationRange: [2, 4] },
            { title: 'Train Plankton Jr. on basic QA (attempt)', durationRange: [2, 3] },
          ],
          durationRange: [2, 4],
          reviewRequired: true,
        },
        {
          id: 'qa-batch-inspection',
          title: 'Continuous Batch QA',
          domain: 'engineering',
          subtasks: [
            { title: 'Inspect batch quality samples', durationRange: [2, 3] },
            { title: 'Reject substandard patties', durationRange: [1, 2] },
            { title: 'Feed quality metrics to dashboard', durationRange: [1, 2] },
            { title: 'Gary meows approval', durationRange: [1, 1] },
          ],
          durationRange: [1, 3],
          reviewRequired: true,
          reviewLoop: { maxIterations: 3, weights: [50, 30, 15, 5] },
          dependsOnTasks: ['qa-framework'],
        },
      ],
    },
    {
      id: 'marketing-coverage',
      title: 'Marketing: Live Coverage',
      phase: 'kitchen-heats-up',
      domains: ['marketing'],
      priority: 'normal',
      description: 'Perch Perkins live-tweets the operation. Larry writes copy. Bubble Bass does SEO.',
      taskTemplates: [
        {
          id: 'live-tweet-setup',
          title: 'Live Tweet Campaign',
          domain: 'marketing',
          subtasks: [
            { title: 'Perch Perkins sets up live stream', durationRange: [1, 2] },
            { title: 'Larry writes hype copy', durationRange: [2, 3] },
            { title: 'Bubble Bass optimizes #10000KrabbyPatties SEO', durationRange: [2, 3] },
            { title: 'Dennis monitors competitor reactions', durationRange: [2, 3] },
          ],
          durationRange: [1, 3],
          reviewRequired: false,
        },
        {
          id: 'ongoing-coverage',
          title: 'Ongoing Media Coverage',
          domain: 'marketing',
          subtasks: [
            { title: 'Hourly production updates', durationRange: [2, 4] },
            { title: 'Customer reaction highlights', durationRange: [2, 3] },
            { title: 'Behind-the-scenes kitchen content', durationRange: [2, 3] },
          ],
          durationRange: [2, 4],
          reviewRequired: false,
          dependsOnTasks: ['live-tweet-setup'],
        },
      ],
    },
    {
      id: 'parallel-security-investigation',
      title: 'Security: Plankton Investigation',
      phase: 'kitchen-heats-up',
      domains: ['security'],
      priority: 'high',
      description: 'Karen deepens the investigation into Plankton\'s motives.',
      dependsOnEpics: ['security-threat-assessment'],
      taskTemplates: [
        {
          id: 'api-access-monitoring',
          title: 'API Access Monitoring',
          domain: 'security',
          subtasks: [
            { title: 'Set up tracking API access logs', durationRange: [2, 3] },
            { title: 'Monitor Plankton\'s access patterns', durationRange: [3, 5] },
            { title: 'Mermaid Man deploys honey tokens', durationRange: [2, 4] },
          ],
          durationRange: [2, 5],
          reviewRequired: true,
        },
        {
          id: 'secret-formula-audit',
          title: 'Secret Formula Access Audit',
          domain: 'security',
          subtasks: [
            { title: 'Audit formula vault access', durationRange: [2, 3] },
            { title: 'Review ingredient supply chain', durationRange: [2, 4] },
            { title: 'Karen runs behavioral analysis on Plankton', durationRange: [3, 5] },
          ],
          durationRange: [2, 5],
          reviewRequired: true,
          dependsOnTasks: ['api-access-monitoring'],
        },
      ],
    },

    // ── ACT 3: Order Up! — The Delivery Crisis ───────────────────────────

    {
      id: 'delivery-operations',
      title: 'Delivery Operations — Squidward Solo',
      phase: 'delivery-crisis',
      domains: ['operations'],
      priority: 'critical',
      description: 'Squidward delivers every batch. Alone. 8 batches/tick while production runs at 50/tick. The queue grows.',
      dependsOnEpics: ['order-intake'],
      taskTemplates: [
        {
          id: 'delivery-setup',
          title: 'Delivery Station Setup',
          domain: 'operations',
          subtasks: [
            { title: 'Squidward prepares delivery trays', durationRange: [1, 2] },
            { title: 'Map table assignments', durationRange: [1, 2] },
            { title: 'Start delivery runs', durationRange: [1, 2] },
          ],
          durationRange: [1, 2],
          reviewRequired: false,
        },
        {
          id: 'delivery-batch-1',
          title: 'Delivery Run — Batches 1-500',
          domain: 'operations',
          subtasks: [
            { title: 'Deliver batches 1-100', durationRange: [4, 6] },
            { title: 'Deliver batches 101-300', durationRange: [5, 8] },
            { title: 'Deliver batches 301-500', durationRange: [5, 8] },
          ],
          durationRange: [4, 8],
          reviewRequired: false,
          dependsOnTasks: ['delivery-setup'],
        },
        {
          id: 'delivery-batch-2',
          title: 'Delivery Run — Batches 501-1500 (errors climbing)',
          domain: 'operations',
          subtasks: [
            { title: 'Deliver batches 501-800 (fatigue setting in)', durationRange: [5, 8] },
            { title: 'Deliver batches 801-1200 (wrong table rate: 5%)', durationRange: [6, 9] },
            { title: 'Deliver batches 1201-1500 (wrong table rate: 12%)', durationRange: [6, 10] },
          ],
          durationRange: [5, 10],
          reviewRequired: true,
          reviewLoop: { maxIterations: 3, weights: [30, 40, 25, 5] },
          dependsOnTasks: ['delivery-batch-1'],
        },
        {
          id: 'delivery-batch-3',
          title: 'Delivery Run — Batches 1501-2500 (crisis mode)',
          domain: 'operations',
          subtasks: [
            { title: 'Deliver batches 1501-1800 (error rate: 18%)', durationRange: [6, 10] },
            { title: 'Deliver batches 1801-2100 (dropped orders!)', durationRange: [7, 11] },
            { title: 'Deliver batches 2101-2500 (Squidward screaming)', durationRange: [7, 12] },
          ],
          durationRange: [6, 12],
          reviewRequired: true,
          reviewLoop: { maxIterations: 4, weights: [20, 30, 35, 15] },
          dependsOnTasks: ['delivery-batch-2'],
        },
      ],
    },
    {
      id: 'order-tracking-ui',
      title: 'Order Tracking UI — Pearl Under Pressure',
      phase: 'delivery-crisis',
      domains: ['frontend'],
      priority: 'high',
      description: 'Pearl must rebuild the order tracking UI to handle the scale.',
      taskTemplates: [
        {
          id: 'tracking-dashboard',
          title: 'Real-Time Order Tracking Dashboard',
          domain: 'frontend',
          subtasks: [
            { title: 'Pearl designs queue visualization', durationRange: [3, 5] },
            { title: 'Build real-time batch status view', durationRange: [3, 5] },
            { title: 'Add delivery progress tracker', durationRange: [3, 4] },
            { title: 'Integrate error rate display', durationRange: [2, 4] },
          ],
          durationRange: [2, 5],
          reviewRequired: true,
          crossDeptTriggers: [
            { action: 'create_task', target: 'Security Review: Tracking Dashboard', domain: 'security', priority: 'normal' },
          ],
        },
        {
          id: 'queue-overflow-ui',
          title: 'Queue Overflow Warning System',
          domain: 'frontend',
          subtasks: [
            { title: 'Build queue depth indicator', durationRange: [2, 3] },
            { title: 'Add backpressure alerts', durationRange: [2, 3] },
            { title: 'Escalation notification system', durationRange: [2, 4] },
          ],
          durationRange: [2, 4],
          reviewRequired: true,
          dependsOnTasks: ['tracking-dashboard'],
        },
      ],
    },
    {
      id: 'support-ticket-surge',
      title: 'Support Ticket Surge — Barnacle Boy\'s Crisis',
      phase: 'delivery-crisis',
      domains: ['operations'],
      priority: 'high',
      description: 'Customer complaints spike. Barnacle Boy, Flying Dutchman, and the Freds scramble.',
      taskTemplates: [
        {
          id: 'ticket-triage',
          title: 'Ticket Triage System',
          domain: 'operations',
          subtasks: [
            { title: 'Barnacle Boy categorizes complaints', durationRange: [2, 3] },
            { title: 'Flying Dutchman handles Tier 2 escalations', durationRange: [3, 5] },
            { title: 'Fred × 3 process basic tickets', durationRange: [3, 5] },
          ],
          durationRange: [2, 5],
          reviewRequired: false,
        },
        {
          id: 'complaint-resolution',
          title: 'Complaint Resolution Pipeline',
          domain: 'operations',
          subtasks: [
            { title: 'Wrong table deliveries — re-route', durationRange: [3, 5] },
            { title: 'Cold patty complaints — re-make queue', durationRange: [3, 5] },
            { title: 'Missing order complaints — track & locate', durationRange: [3, 5] },
            { title: 'Escalate unresolvable to Barnacle Boy', durationRange: [2, 4] },
          ],
          durationRange: [2, 5],
          reviewRequired: true,
          reviewLoop: { maxIterations: 3, weights: [40, 35, 20, 5] },
          dependsOnTasks: ['ticket-triage'],
        },
      ],
    },

    // ── ACT 4: The Bottleneck ─────────────────────────────────────────────

    {
      id: 'resource-reallocation',
      title: 'Resource Reallocation — THE DECISION',
      phase: 'the-bottleneck',
      domains: ['operations', 'engineering'],
      priority: 'critical',
      description: 'Mr. Krabs faces the decision: spend money to reallocate Pearl + Fred to delivery, or let the order fail.',
      taskTemplates: [
        {
          id: 'escalation-report',
          title: 'Squidward\'s Escalation Report',
          domain: 'operations',
          subtasks: [
            { title: 'Squidward: "I CAN\'T DELIVER 10,000 BY MYSELF"', durationRange: [1, 2] },
            { title: 'Queue depth report: 200+ batches backed up', durationRange: [1, 2] },
            { title: 'Error rate report: 18% and climbing', durationRange: [1, 2] },
          ],
          durationRange: [1, 2],
          reviewRequired: false,
        },
        {
          id: 'krabs-decision',
          title: 'Mr. Krabs Makes THE DECISION',
          domain: 'operations',
          subtasks: [
            { title: 'Review cost of reallocation vs lost revenue', durationRange: [2, 3] },
            { title: 'Krabs reluctantly approves overtime budget', durationRange: [1, 2] },
            { title: 'Reassign Pearl from frontend to delivery', durationRange: [1, 2] },
            { title: 'Reassign Fred ×3 from support to delivery', durationRange: [1, 2] },
          ],
          durationRange: [1, 3],
          reviewRequired: true,
          reviewLoop: { maxIterations: 2, weights: [70, 20, 10, 0] },
          dependsOnTasks: ['escalation-report'],
          crossDeptTriggers: [
            { action: 'unlock_epic', target: 'scaled-delivery' },
            { action: 'create_task', target: 'Overtime Cost Impact Analysis', domain: 'finance', priority: 'high' },
          ],
        },
      ],
    },
    {
      id: 'overtime-cost-analysis',
      title: 'Overtime Cost Analysis — Squilliam\'s Warning',
      phase: 'the-bottleneck',
      domains: ['finance'],
      priority: 'high',
      description: 'Squilliam warns that overtime costs are eating the profit margin.',
      taskTemplates: [
        {
          id: 'overtime-projection',
          title: 'Overtime Cost Projection',
          domain: 'finance',
          subtasks: [
            { title: 'Calculate overtime labor costs', durationRange: [2, 3] },
            { title: 'Plankton runs margin erosion analysis', durationRange: [2, 4] },
            { title: 'Mrs. Puff updates P&L with overtime', durationRange: [2, 3] },
            { title: 'Squilliam warns Krabs: margins thin', durationRange: [1, 2] },
          ],
          durationRange: [1, 4],
          reviewRequired: true,
        },
      ],
    },
    {
      id: 'kitchen-idle-management',
      title: 'Kitchen Idle Management',
      phase: 'the-bottleneck',
      domains: ['engineering'],
      priority: 'normal',
      description: 'SpongeBob\'s team starts idling — blocked by delivery capacity. Backpressure hits production.',
      taskTemplates: [
        {
          id: 'backpressure-response',
          title: 'Backpressure Response',
          domain: 'engineering',
          subtasks: [
            { title: 'SpongeBob throttles production rate', durationRange: [1, 2] },
            { title: 'Sandy optimizes batch sizes for delivery', durationRange: [2, 4] },
            { title: 'Patrick takes a nap (scheduled idle)', durationRange: [1, 2] },
            { title: 'Gary maintains QA during slowdown', durationRange: [2, 3] },
          ],
          durationRange: [1, 4],
          reviewRequired: false,
        },
      ],
    },

    // ── ACT 5: The Pipeline Balances ──────────────────────────────────────

    {
      id: 'scaled-delivery',
      title: 'Scaled Delivery — Triple Throughput',
      phase: 'pipeline-balances',
      domains: ['operations'],
      priority: 'critical',
      description: 'Pearl + Fred join Squidward. Delivery rate triples to 24 batches/tick.',
      dependsOnEpics: ['resource-reallocation'],
      taskTemplates: [
        {
          id: 'delivery-onboarding',
          title: 'Delivery Team Onboarding',
          domain: 'operations',
          subtasks: [
            { title: 'Pearl learns table routing', durationRange: [2, 3] },
            { title: 'Fred ×3 briefed on delivery protocol', durationRange: [2, 3] },
            { title: 'Squidward distributes routes', durationRange: [1, 2] },
          ],
          durationRange: [1, 3],
          reviewRequired: false,
        },
        {
          id: 'delivery-batch-4',
          title: 'Scaled Delivery — Batches 2501-5000',
          domain: 'operations',
          subtasks: [
            { title: 'Squidward delivers 2501-3500', durationRange: [4, 6] },
            { title: 'Pearl delivers 3501-4200', durationRange: [4, 6] },
            { title: 'Fred team delivers 4201-5000', durationRange: [4, 6] },
          ],
          durationRange: [4, 6],
          reviewRequired: false,
          dependsOnTasks: ['delivery-onboarding'],
        },
        {
          id: 'delivery-batch-5',
          title: 'Scaled Delivery — Batches 5001-7500',
          domain: 'operations',
          subtasks: [
            { title: 'Parallel delivery: 3 routes active', durationRange: [4, 6] },
            { title: 'Queue draining — depth dropping', durationRange: [4, 6] },
            { title: 'Error rate recovering: 18% → 5%', durationRange: [3, 5] },
          ],
          durationRange: [3, 6],
          reviewRequired: true,
          reviewLoop: { maxIterations: 2, weights: [70, 25, 5, 0] },
          dependsOnTasks: ['delivery-batch-4'],
        },
        {
          id: 'delivery-batch-6',
          title: 'Scaled Delivery — Batches 7501-10000 (THE HOME STRETCH)',
          domain: 'operations',
          subtasks: [
            { title: 'Deliver batches 7501-8500', durationRange: [4, 6] },
            { title: 'Deliver batches 8501-9500', durationRange: [4, 6] },
            { title: 'Deliver batches 9501-10000 — DONE!', durationRange: [3, 5] },
          ],
          durationRange: [3, 6],
          reviewRequired: false,
          dependsOnTasks: ['delivery-batch-5'],
        },
      ],
    },
    {
      id: 'final-push',
      title: 'Final Production Push',
      phase: 'pipeline-balances',
      domains: ['engineering'],
      priority: 'high',
      description: 'Kitchen resumes full speed as delivery unblocks. Final batches produced.',
      taskTemplates: [
        {
          id: 'resume-production',
          title: 'Resume Full Production',
          domain: 'engineering',
          subtasks: [
            { title: 'SpongeBob cranks grills back to max', durationRange: [1, 2] },
            { title: 'Sandy monitors pipeline throughput', durationRange: [2, 3] },
            { title: 'Patrick executes final batches', durationRange: [3, 5] },
            { title: 'Gary final QA sweep', durationRange: [2, 3] },
          ],
          durationRange: [1, 5],
          reviewRequired: true,
        },
      ],
    },
    {
      id: 'financial-reconciliation',
      title: 'Financial Reconciliation — Squilliam\'s Final P&L',
      phase: 'pipeline-balances',
      domains: ['finance'],
      priority: 'high',
      description: 'Squilliam prepares the final profit & loss statement.',
      taskTemplates: [
        {
          id: 'final-pnl',
          title: 'Final P&L Statement',
          domain: 'finance',
          subtasks: [
            { title: 'Compile total ingredient costs', durationRange: [2, 3] },
            { title: 'Compile total labor costs (incl. overtime)', durationRange: [2, 3] },
            { title: 'Calculate waste from rejected batches', durationRange: [2, 3] },
            { title: 'Plankton runs final analytics', durationRange: [2, 3] },
            { title: 'Mrs. Puff finalizes books', durationRange: [1, 2] },
            { title: 'Squilliam presents to Mr. Krabs', durationRange: [1, 2] },
          ],
          durationRange: [1, 3],
          reviewRequired: true,
          reviewLoop: { maxIterations: 2, weights: [70, 25, 5, 0] },
        },
      ],
    },
    {
      id: 'security-final-report',
      title: 'Security Final Report — Karen\'s Verdict',
      phase: 'pipeline-balances',
      domains: ['security'],
      priority: 'normal',
      description: 'Karen reports Plankton accessed the tracking API 47 times — but no breach detected.',
      taskTemplates: [
        {
          id: 'security-summary',
          title: 'Security Investigation Summary',
          domain: 'security',
          subtasks: [
            { title: 'Compile API access log: 47 accesses by Plankton', durationRange: [2, 3] },
            { title: 'Mermaid Man confirms: no breach detected', durationRange: [2, 3] },
            { title: 'Karen: "He was just... tracking his order"', durationRange: [1, 2] },
            { title: 'Close investigation — no formula compromise', durationRange: [1, 2] },
          ],
          durationRange: [1, 3],
          reviewRequired: false,
        },
        {
          id: 'post-incident-report',
          title: 'Post-Incident Security Report',
          domain: 'security',
          subtasks: [
            { title: 'Document findings', durationRange: [2, 3] },
            { title: 'Recommend API rate limits for future', durationRange: [2, 3] },
            { title: 'File report with Mr. Krabs', durationRange: [1, 2] },
          ],
          durationRange: [1, 3],
          reviewRequired: true,
          dependsOnTasks: ['security-summary'],
        },
      ],
    },
  ],

  // ── Events ───────────────────────────────────────────────────────────────

  events: [
    {
      id: 'grill-malfunction',
      name: 'Grill Malfunction',
      type: 'interrupt',
      probability: 0.05,
      cooldownTicks: 25,
      narrative: '🔥 One of Sandy\'s parallel grill stations overheated! Patrick is panicking. Production drops temporarily.',
      effect: {
        createTasks: [
          {
            title: 'Repair grill station',
            domain: 'engineering',
            priority: 'critical',
            subtaskCount: 3,
            durationRange: [2, 4],
          },
        ],
        blockAgents: { domain: 'backend', count: 1, durationTicks: 8 },
      },
    },
    {
      id: 'ingredient-shortage',
      name: 'Ingredient Shortage',
      type: 'disruption',
      probability: 0.04,
      cooldownTicks: 30,
      maxOccurrences: 2,
      narrative: '🥬 We\'re running low on secret sauce! Sandy dispatches Patrick to the supplier. Production slows.',
      effect: {
        createTasks: [
          {
            title: 'Emergency ingredient resupply',
            domain: 'operations',
            priority: 'high',
            subtaskCount: 3,
            durationRange: [3, 5],
          },
        ],
        resourceEffect: { 'ingredients': -15 },
      },
    },
    {
      id: 'intern-disaster',
      name: 'Plankton Jr. Incident',
      type: 'interrupt',
      probability: 0.03,
      cooldownTicks: 80,
      maxOccurrences: 1,
      narrative: '🦠 Plankton Jr. accidentally dumped a batch into the wrong container. Gary is NOT happy. QA cycle triggered.',
      effect: {
        createTasks: [
          {
            title: 'Salvage contaminated batch',
            domain: 'engineering',
            priority: 'high',
            subtaskCount: 3,
            durationRange: [2, 4],
          },
          {
            title: 'Retrain Plankton Jr. (again)',
            domain: 'engineering',
            priority: 'normal',
            subtaskCount: 2,
            durationRange: [2, 3],
          },
        ],
      },
    },
    {
      id: 'squidward-drops-order',
      name: 'Squidward Drops an Order',
      type: 'interrupt',
      probability: 0.06,
      cooldownTicks: 15,
      narrative: '🐙 Squidward dropped a tray of 50 patties! They need to be re-made AND re-delivered.',
      effect: {
        createTasks: [
          {
            title: 'Re-make dropped batch',
            domain: 'backend',
            priority: 'high',
            subtaskCount: 2,
            durationRange: [2, 4],
          },
          {
            title: 'Re-deliver dropped batch',
            domain: 'operations',
            priority: 'high',
            subtaskCount: 1,
            durationRange: [2, 3],
          },
        ],
      },
    },
    {
      id: 'wrong-table-delivery',
      name: 'Wrong Table Delivery',
      type: 'disruption',
      probability: 0.07,
      cooldownTicks: 10,
      narrative: '🪑 Squidward delivered to the WRONG TABLE again. Complaints incoming.',
      effect: {
        createTasks: [
          {
            title: 'Re-route misdelivered order',
            domain: 'operations',
            priority: 'high',
            subtaskCount: 2,
            durationRange: [1, 3],
          },
        ],
        elevatePriority: 1,
      },
    },
    {
      id: 'customer-complaint-wave',
      name: 'Customer Complaint Wave',
      type: 'expansion',
      probability: 0.05,
      cooldownTicks: 20,
      narrative: '📱 Support tickets spiking! "WHERE\'S MY ORDER?!" Barnacle Boy needs backup.',
      effect: {
        expandEpic: {
          taskCount: 3,
          domain: 'operations',
          priority: 'high',
        },
      },
    },
    {
      id: 'plankton-suspicious-activity',
      name: 'Plankton Suspicious Activity',
      type: 'narrative',
      probability: 0.04,
      cooldownTicks: 30,
      maxOccurrences: 4,
      narrative: '🧫 Karen detected Plankton accessing the tracking API again. That\'s access #${count}. Mermaid Man is watching.',
      effect: {
        createTasks: [
          {
            title: 'Investigate Plankton API access',
            domain: 'security',
            priority: 'normal',
            subtaskCount: 1,
            durationRange: [1, 3],
          },
        ],
      },
    },
    {
      id: 'squidward-meltdown',
      name: 'Squidward\'s Meltdown',
      type: 'interrupt',
      probability: 0.08,
      cooldownTicks: 40,
      maxOccurrences: 1,
      durationTicks: 10,
      narrative: '🐙💀 Squidward has SNAPPED. "I QUIT! I\'M DONE! I\'M—" Mr. Krabs talks him down. 10-tick slowdown.',
      effect: {
        blockAgents: { role: 'operations', count: 1, durationTicks: 10 },
        createTasks: [
          {
            title: 'Mr. Krabs motivational speech',
            domain: 'operations',
            priority: 'critical',
            subtaskCount: 2,
            durationRange: [2, 3],
          },
        ],
      },
    },
    {
      id: 'overtime-budget-alert',
      name: 'Overtime Budget Alert',
      type: 'modifier',
      probability: 0.06,
      cooldownTicks: 30,
      maxOccurrences: 2,
      narrative: '💰 Squilliam: "The overtime is eating our margin!" Mrs. Puff confirms — costs up 40%.',
      effect: {
        resourceEffect: { 'budget': -200 },
      },
    },
  ],

  // ── Resources ────────────────────────────────────────────────────────────

  resources: [
    {
      id: 'ingredients',
      name: 'Krabby Patty Ingredients',
      type: 'compute',
      initial: 200,
      burnRate: 0.5,
      alertThresholdPct: 15,
      depletedEffect: 'pause-all',
    },
    {
      id: 'grill-capacity',
      name: 'Grill Capacity',
      type: 'compute',
      initial: 100,
      burnRate: 0.3,
      alertThresholdPct: 20,
      depletedEffect: 'pause-non-critical',
    },
    {
      id: 'delivery-capacity',
      name: 'Delivery Capacity',
      type: 'agent-hours',
      initial: 80,
      burnRate: 0.4,
      alertThresholdPct: 25,
      depletedEffect: 'none',
    },
    {
      id: 'budget',
      name: 'Operation Budget',
      type: 'credits',
      initial: 10000,
      burnRate: 15,
      alertThresholdPct: 20,
      depletedEffect: 'pause-non-critical',
    },
    {
      id: 'support-bandwidth',
      name: 'Support Bandwidth',
      type: 'agent-hours',
      initial: 60,
      burnRate: 0.2,
      alertThresholdPct: 30,
      depletedEffect: 'none',
    },
  ],

  // ── Scoring ──────────────────────────────────────────────────────────────

  scoring: {
    dimensions: [
      { id: 'throughput', name: 'Throughput', description: 'Patties produced and delivered per tick' },
      { id: 'quality', name: 'Quality', description: 'Batch QA pass rate and delivery accuracy' },
      { id: 'efficiency', name: 'Efficiency', description: 'Resource utilization and waste minimization' },
      { id: 'resilience', name: 'Resilience', description: 'Recovery from bottlenecks and events' },
      { id: 'customer-satisfaction', name: 'Customer Satisfaction', description: 'Complaint rate and resolution speed' },
      { id: 'profitability', name: 'Profitability', description: 'Final P&L — revenue vs costs' },
    ],
    weights: {
      throughput: 25,
      quality: 20,
      efficiency: 15,
      resilience: 20,
      'customer-satisfaction': 10,
      profitability: 10,
    },
    grades: [
      { grade: 'S', minScore: 90, label: 'Krabby Patty PERFECTION. Mr. Krabs is crying tears of joy.' },
      { grade: 'A', minScore: 80, label: 'Outstanding operation. Squidward only complained twice.' },
      { grade: 'B', minScore: 70, label: 'Solid delivery. Some hiccups but the patties got there.' },
      { grade: 'C', minScore: 60, label: 'Rough around the edges. Too many wrong tables.' },
      { grade: 'D', minScore: 50, label: 'Squidward quit halfway through. Barely survived.' },
      { grade: 'F', minScore: 0, label: 'Total kitchen meltdown. Plankton got a refund.' },
    ],
  },
};
