/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      screens: {
        'landscape': { 'raw': '(orientation: landscape) and (max-height: 500px)' },
        'portrait': { 'raw': '(orientation: portrait)' },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Baloo 2"', 'cursive'],
        body: ['Nunito', 'sans-serif'],
      },
      colors: {
        'bb-sandy': {
          DEFAULT: '#F4C542',
          50:  '#FFFBEB',
          100: '#FEF3C7',
          200: '#FDE68A',
          300: '#FCD34D',
          400: '#F4C542',
          500: '#EAB308',
          600: '#D4952A',
          700: '#B45309',
          800: '#92400E',
          900: '#78350F',
        },
        'bb-ocean': {
          DEFAULT: '#0B5E8A',
          abyss:  '#030E1A',
          900:    '#062A45',
          800:    '#0B3D60',
          700:    '#0B5E8A',
          600:    '#1A7DB5',
          500:    '#2E97D1',
          400:    '#4AAED9',
          300:    '#7EC8E8',
          200:    '#B8E4F7',
          100:    '#D6F0FA',
          50:     '#E8F8FF',
        },
        'bb-coral': {
          DEFAULT: '#FF6B6B',
          900: '#7F1D1D',
          700: '#B91C1C',
          500: '#FF4757',
          400: '#FF6B6B',
          300: '#FF8E8E',
          200: '#FFB3B3',
          100: '#FFD9D9',
        },
        'bb-kelp': {
          DEFAULT: '#2ECC71',
          900: '#064E3B',
          700: '#065F46',
          600: '#1A8A4A',
          500: '#2ECC71',
          400: '#4AE88A',
          300: '#6EF2A4',
          200: '#A7F3C8',
          100: '#D1FAE5',
        },
        'bb-krabby':  '#C0392B',
        'bb-pineapple': '#FFD43B',
        'bb-bubble':  '#E8F8FF',
        'bb-squid':   '#9B59B6',
        'bb-pearl':   '#FF85C2',
        'bb-dutchman': '#76D7C4',
      },
      animation: {
        'bb-bob':        'bb-bob 2s ease-in-out infinite',
        'bb-bob-fast':   'bb-bob-fast 1s ease-in-out infinite',
        'bb-jitter':     'bb-jitter 0.4s ease-in-out infinite',
        'bb-bubble-float': 'bb-bubble-float 12s ease-in-out infinite',
        'bb-kelp-sway':  'bb-kelp-sway 4s ease-in-out infinite',
        'bb-swim':       'bb-swim 30s linear infinite',
        'bb-caustic':    'bb-caustic 12s ease-in-out infinite',
        'bb-pulse-ring': 'bb-pulse-ring 2s ease-in-out infinite',
        'bb-pulse-coral': 'bb-pulse-ring-coral 1.5s ease-in-out infinite',
        'bb-shimmer':    'bb-shimmer 2s linear infinite',
        'bb-enter-up':   'bb-enter-up 0.4s ease-out',
        'bb-enter-scale': 'bb-enter-scale 0.3s ease-out',
        'ping-slow':     'ping 2s cubic-bezier(0,0,0.2,1) infinite',
      },
      keyframes: {
        'bb-bob': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-4px)' },
        },
        'bb-bob-fast': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-3px)' },
        },
        'bb-jitter': {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%':      { transform: 'translateX(-2px) rotate(-1deg)' },
          '40%':      { transform: 'translateX(2px) rotate(1deg)' },
          '60%':      { transform: 'translateX(-1.5px)' },
          '80%':      { transform: 'translateX(1.5px)' },
        },
        'bb-bubble-float': {
          '0%':   { transform: 'translateY(0) translateX(0) scale(1)', opacity: '0' },
          '5%':   { opacity: '0.5' },
          '50%':  { transform: 'translateY(-50vh) translateX(8px) scale(0.9)', opacity: '0.4' },
          '95%':  { opacity: '0.2' },
          '100%': { transform: 'translateY(-100vh) translateX(-4px) scale(0.6)', opacity: '0' },
        },
        'bb-kelp-sway': {
          '0%, 100%': { transform: 'skewX(0deg) scaleY(1)', transformOrigin: 'bottom center' },
          '25%':      { transform: 'skewX(3deg) scaleY(1.01)', transformOrigin: 'bottom center' },
          '75%':      { transform: 'skewX(-3deg) scaleY(0.99)', transformOrigin: 'bottom center' },
        },
        'bb-swim': {
          '0%':   { transform: 'translateX(110vw)' },
          '100%': { transform: 'translateX(-20vw)' },
        },
        'bb-caustic': {
          '0%, 100%': { opacity: '0.04', transform: 'scale(1) rotate(0deg)' },
          '33%':      { opacity: '0.07', transform: 'scale(1.1) rotate(2deg)' },
          '66%':      { opacity: '0.05', transform: 'scale(0.95) rotate(-1deg)' },
        },
        'bb-pulse-ring': {
          '0%, 100%': { boxShadow: '0 0 0 0px rgba(244,197,66,0.4)' },
          '50%':      { boxShadow: '0 0 0 8px rgba(244,197,66,0)' },
        },
        'bb-pulse-ring-coral': {
          '0%, 100%': { boxShadow: '0 0 0 0px rgba(255,71,87,0.4)' },
          '50%':      { boxShadow: '0 0 0 8px rgba(255,71,87,0)' },
        },
        'bb-shimmer': {
          '0%':   { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        'bb-enter-up': {
          'from': { opacity: '0', transform: 'translateY(12px)' },
          'to':   { opacity: '1', transform: 'translateY(0)' },
        },
        'bb-enter-scale': {
          'from': { opacity: '0', transform: 'scale(0.92)' },
          'to':   { opacity: '1', transform: 'scale(1)' },
        },
      },
    },
  },
  plugins: [],
};
