/**
 * BikiniBottom Agent Roster — all 22 characters with their metadata.
 * Used by CharacterCardGrid on the landing page and agent detail panels.
 */

import type { AgentCharacter } from "./CharacterCard";

export const AGENT_ROSTER: AgentCharacter[] = [
  {
    id: "mr-krabs",
    name: "Mr. Krabs",
    emoji: "🦀",
    avatarUrl: "/app/avatars/mr-krabs.png",
    jobTitle: "CEO / The Bottom Line",
    team: "Operations",
    cardClass: "bb-card-krabs",
    accentColor: "#C0392B",
    status: "working",
    lastMessage: "MONEY MONEY MONEY! Cook faster, boy!",
  },
  {
    id: "spongebob-squarepants",
    name: "SpongeBob",
    emoji: "🧽",
    avatarUrl: "/app/avatars/spongebob.png",
    jobTitle: "Head Chef / VP Kitchen",
    team: "Kitchen Ops",
    cardClass: "bb-card-spongebob",
    accentColor: "#FFD43B",
    status: "working",
    lastMessage: "Batch 47 started — 500 patties underway!",
  },
  {
    id: "squidward-tentacles",
    name: "Squidward",
    emoji: "🐙",
    avatarUrl: "/app/avatars/squidward.png",
    jobTitle: "Delivery Manager",
    team: "Delivery",
    cardClass: "bb-card-squidward",
    accentColor: "#9B59B6",
    status: "busy",
    queueSize: 203,
    lastMessage: "I CANNOT deliver 200 batches alone. This is not what I signed up for.",
  },
  {
    id: "squilliam-fancyson",
    name: "Squilliam",
    emoji: "🎩",
    avatarUrl: "/app/avatars/squilliam.png",
    jobTitle: "CFO / The Vault",
    team: "Finance",
    accentColor: "#6366F1",
    status: "working",
    lastMessage: "Revenue is up 340%. Even I am impressed.",
  },
  {
    id: "sandy-cheeks",
    name: "Sandy Cheeks",
    emoji: "🐿️",
    avatarUrl: "/app/avatars/sandy.png",
    jobTitle: "Head of Engineering",
    team: "Kitchen Engineering",
    cardClass: "bb-card-sandy",
    accentColor: "#16A085",
    status: "working",
    lastMessage: "Optimizing the spatula algorithm for 15% throughput gain.",
  },
  {
    id: "karen",
    name: "Karen",
    emoji: "🖥️",
    avatarUrl: "/app/avatars/karen.png",
    jobTitle: "AI Systems / Computer",
    team: "Tech",
    cardClass: "bb-card-karen",
    accentColor: "#4AAED9",
    status: "working",
    lastMessage: "All systems nominal. Plankton, please stop asking me to betray Mr. Krabs.",
  },
  {
    id: "pearl-krabs",
    name: "Pearl Krabs",
    emoji: "🐳",
    avatarUrl: "/app/avatars/pearl.png",
    jobTitle: "Customer Success",
    team: "Register",
    accentColor: "#FF85C2",
    status: "working",
    lastMessage: "Like, OMG, Plankton just ordered 10,000 more??",
  },
  {
    id: "perch-perkins",
    name: "Perch Perkins",
    emoji: "🐟",
    jobTitle: "Head of PR / Media",
    team: "Communications",
    accentColor: "#F59E0B",
    status: "idle",
    lastMessage: "Breaking news: Krusty Krab hits record deliveries!",
  },
  {
    id: "barnacle-boy",
    name: "Barnacle Boy",
    emoji: "🦸",
    avatarUrl: "/app/avatars/barnacle-boy.png",
    jobTitle: "Security Team Lead",
    team: "Security",
    accentColor: "#1E3A5F",
    status: "idle",
    lastMessage: "Perimeter secure. No Plankton infiltration detected.",
  },
  {
    id: "plankton",
    name: "Plankton",
    emoji: "🦠",
    avatarUrl: "/app/avatars/plankton.png",
    jobTitle: "Competitive Intelligence",
    team: "…Intern",
    cardClass: "bb-card-plankton",
    accentColor: "#1E8449",
    status: "busy",
    lastMessage:
      "All I wanted was the secret formula. Now I have 10,000 patties. This was not the plan.",
  },
  {
    id: "mrs-puff",
    name: "Mrs. Puff",
    emoji: "🐠",
    avatarUrl: "/app/avatars/mrs-puff.png",
    jobTitle: "Training & Safety",
    team: "Operations",
    accentColor: "#F97316",
    status: "idle",
    lastMessage: "SpongeBob passed spatula certification. I am shocked.",
  },
  {
    id: "patrick-star",
    name: "Patrick Star",
    emoji: "⭐",
    avatarUrl: "/app/avatars/patrick.png",
    jobTitle: "Sous Chef (Enthusiastic)",
    team: "Kitchen Ops",
    cardClass: "bb-card-patrick",
    accentColor: "#F1948A",
    status: "working",
    lastMessage: "Is mayonnaise an instrument? Also I made 200 patties somehow.",
  },
  {
    id: "gary",
    name: "Gary",
    emoji: "🐌",
    avatarUrl: "/app/avatars/gary.png",
    jobTitle: "Systems Monitor",
    team: "Kitchen Ops",
    accentColor: "#10B981",
    status: "idle",
    lastMessage: "Meow.",
  },
  {
    id: "plankton-jr",
    name: "Plankton Jr.",
    emoji: "🧫",
    jobTitle: "Data Analytics",
    team: "Finance",
    accentColor: "#84CC16",
    status: "working",
    lastMessage: "Dashboard shows 7,240 patties delivered. Chart going up.",
  },
  {
    id: "mermaid-man",
    name: "Mermaid Man",
    emoji: "🦸",
    avatarUrl: "/app/avatars/mermaid-man.png",
    jobTitle: "Legacy Systems Support",
    team: "Engineering",
    accentColor: "#EAB308",
    status: "idle",
    lastMessage: "EVIL! Also the old fryer still works fine.",
  },
  {
    id: "larry-lobster",
    name: "Larry the Lobster",
    emoji: "🦞",
    avatarUrl: "/app/avatars/larry.png",
    jobTitle: "Delivery Agent",
    team: "Delivery",
    accentColor: "#DC2626",
    status: "working",
    lastMessage: "Bro I just delivered batch 32. Arms are pumped.",
  },
  {
    id: "bubble-bass",
    name: "Bubble Bass",
    emoji: "🐡",
    jobTitle: "Quality Assurance",
    team: "QA",
    accentColor: "#0891B2",
    status: "working",
    lastMessage: "You forgot the pickles. AGAIN. Batch 46 rejected.",
  },
  {
    id: "dennis",
    name: "Dennis",
    emoji: "🕶️",
    jobTitle: "Security Enforcement",
    team: "Security",
    accentColor: "#374151",
    status: "idle",
    lastMessage: "Nobody leaves without their receipt.",
  },
  {
    id: "flying-dutchman",
    name: "Flying Dutchman",
    emoji: "👻",
    avatarUrl: "/app/avatars/flying-dutchman.png",
    jobTitle: "Ghost Accountant",
    team: "Finance",
    accentColor: "#76D7C4",
    status: "idle",
    lastMessage: "I have audited the books. Mr. Krabs owes me one shiny dime.",
  },
  {
    id: "fred-1",
    name: "Fred-1",
    emoji: "🧑",
    jobTitle: "Delivery Agent (Fred)",
    team: "Delivery",
    accentColor: "#6B7280",
    status: "working",
    lastMessage: "MY LEG!!! But also I delivered 50 orders.",
  },
  {
    id: "fred-2",
    name: "Fred-2",
    emoji: "🧑",
    jobTitle: "Delivery Agent (Fred's Clone)",
    team: "Delivery",
    accentColor: "#9CA3AF",
    status: "working",
    lastMessage: "MY LEG!!! Route 7 complete.",
  },
  {
    id: "fred-3",
    name: "Fred-3",
    emoji: "🧑",
    jobTitle: "Delivery Agent (Fred's Clone)",
    team: "Delivery",
    accentColor: "#D1D5DB",
    status: "working",
    lastMessage: "MY LEG!!! But batch 38 is on the way.",
  },
];

/** Sample live ticker messages for the landing page */
export const SAMPLE_TICKER_MESSAGES = [
  {
    id: "t1",
    agentEmoji: "🦀",
    agentName: "Mr. Krabs",
    text: "COOK FASTER BOY — Plankton wants 10,000!",
    type: "delegation" as const,
  },
  {
    id: "t2",
    agentEmoji: "🧽",
    agentName: "SpongeBob",
    text: "Batch 47 started — 500 patties incoming",
    type: "message" as const,
  },
  {
    id: "t3",
    agentEmoji: "🐙",
    agentName: "Squidward",
    text: "I CANNOT deliver 200 batches alone",
    type: "escalation" as const,
  },
  {
    id: "t4",
    agentEmoji: "🦀",
    agentName: "Mr. Krabs",
    text: "Then get help. Fred-1, Fred-2, Fred-3 — hired.",
    type: "delegation" as const,
  },
  {
    id: "t5",
    agentEmoji: "📦",
    agentName: "System",
    text: "Delivery rate ↑ 340% — Fred-1/2/3 joined team",
    type: "completion" as const,
  },
  {
    id: "t6",
    agentEmoji: "🐡",
    agentName: "Bubble Bass",
    text: "You forgot the pickles. BATCH 46 REJECTED.",
    type: "escalation" as const,
  },
  {
    id: "t7",
    agentEmoji: "🧽",
    agentName: "SpongeBob",
    text: "Sorry! Adding pickles. Batch 46r in progress.",
    type: "message" as const,
  },
  {
    id: "t8",
    agentEmoji: "🐿️",
    agentName: "Sandy",
    text: "Spatula algorithm upgraded. Throughput +15%!",
    type: "completion" as const,
  },
  {
    id: "t9",
    agentEmoji: "⭐",
    agentName: "Patrick",
    text: "Is mayonnaise a patty? I made 200 somehow.",
    type: "message" as const,
  },
  {
    id: "t10",
    agentEmoji: "🦞",
    agentName: "Larry",
    text: "Batch 32 delivered. Arms are pumped. 💪",
    type: "completion" as const,
  },
];
